# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentclash" do
  version "0.9.0"

  on_macos do
    on_intel do
      sha256 "de9de6e86b35bb6ede3ad24cb5296362288c0e8b9d265c103a58f71fd6361158"
      url "https://github.com/agentclash/agentclash/releases/download/v#{version}/agentclash_darwin_amd64.tar.gz",
        verified: "github.com/agentclash/agentclash"
    end
    on_arm do
      sha256 "51caa1a5a7d6698a540041fe868a1048e5d8d5564981757e0d19288c1b9fca86"
      url "https://github.com/agentclash/agentclash/releases/download/v#{version}/agentclash_darwin_arm64.tar.gz",
        verified: "github.com/agentclash/agentclash"
    end
  end

  on_linux do
    on_intel do
      sha256 "aa428bc249a3c4ba61322e03f6c9406f161e00024a1ccb3c9716d2c16dcec139"
      url "https://github.com/agentclash/agentclash/releases/download/v#{version}/agentclash_linux_amd64.tar.gz",
        verified: "github.com/agentclash/agentclash"
    end
    on_arm do
      sha256 "7c5daad8850aff03dd9646c73fee5d665ef0676667b0a94b1ad02d16c5c89316"
      url "https://github.com/agentclash/agentclash/releases/download/v#{version}/agentclash_linux_arm64.tar.gz",
        verified: "github.com/agentclash/agentclash"
    end
  end

  name "agentclash"
  desc "CLI for the AgentClash AI agent evaluation platform"
  homepage "https://github.com/agentclash/agentclash"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentclash"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agentclash"]
    end
  end

  # No zap stanza required

end
