# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentclash" do
  version "2.1.2"

  on_macos do
    on_intel do
      sha256 "001022a810d5415e9f441f88c8366c60dd1568a782834979a2b80af23bd30044"
      url "https://github.com/agentclash/agentclash/releases/download/v#{version}/agentclash_darwin_amd64.tar.gz",
        verified: "github.com/agentclash/agentclash"
    end
    on_arm do
      sha256 "2ae9c1c9707b03e14bb848b1e5f46713c87c1a20cf4fb8cd1509e2f31de4ccc7"
      url "https://github.com/agentclash/agentclash/releases/download/v#{version}/agentclash_darwin_arm64.tar.gz",
        verified: "github.com/agentclash/agentclash"
    end
  end

  on_linux do
    on_intel do
      sha256 "0a388765c3538fecbec69c9faf8bc16f7cd246b3f5ecf3d9552aef567c24b288"
      url "https://github.com/agentclash/agentclash/releases/download/v#{version}/agentclash_linux_amd64.tar.gz",
        verified: "github.com/agentclash/agentclash"
    end
    on_arm do
      sha256 "c79d0bcf45725a729ebadf348688b876fb81a913645404bd17a9b7fe035457cb"
      url "https://github.com/agentclash/agentclash/releases/download/v#{version}/agentclash_linux_arm64.tar.gz",
        verified: "github.com/agentclash/agentclash"
    end
  end

  name "agentclash"
  desc "CLI for the AgentClash AI agent evaluation platform"
  homepage "https://github.com/agentclash/agentclash"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentclash"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agentclash"]
    end
  end

  # No zap stanza required

end
