# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentclash" do
  version "0.14.1"

  on_macos do
    on_intel do
      sha256 "12dcfcbaa995729b90723d9b76f9b97d6bb4c354ffc04eefc8c43cfd48972f05"
      url "https://github.com/agentclash/agentclash/releases/download/v#{version}/agentclash_darwin_amd64.tar.gz",
        verified: "github.com/agentclash/agentclash"
    end
    on_arm do
      sha256 "9cb46243c7a4b91c6bf7e750dfafbacfdf7cc6fe70b6e5ba26eecc7b6bf68598"
      url "https://github.com/agentclash/agentclash/releases/download/v#{version}/agentclash_darwin_arm64.tar.gz",
        verified: "github.com/agentclash/agentclash"
    end
  end

  on_linux do
    on_intel do
      sha256 "20b85ceac49e57f2e71133bde62765799a39125bb34d4c85e011e3b733f331c0"
      url "https://github.com/agentclash/agentclash/releases/download/v#{version}/agentclash_linux_amd64.tar.gz",
        verified: "github.com/agentclash/agentclash"
    end
    on_arm do
      sha256 "1f618cc81ef655129aac4dd437387ba425ad2d136c6477a0f7c5c9b15d3749ee"
      url "https://github.com/agentclash/agentclash/releases/download/v#{version}/agentclash_linux_arm64.tar.gz",
        verified: "github.com/agentclash/agentclash"
    end
  end

  name "agentclash"
  desc "CLI for the AgentClash AI agent evaluation platform"
  homepage "https://github.com/agentclash/agentclash"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentclash"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agentclash"]
    end
  end

  # No zap stanza required

end
